"""extended training job table

Revision ID: b22e8bbce717
Revises: 283fd209baf9
Create Date: 2026-09-21 00:47:45.865273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b22e8bbce717'
down_revision: Union[str, Sequence[str], None] = '283fd209baf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_jobs', sa.Column('current_trial', sa.Integer(), nullable=True))
    op.add_column('training_jobs', sa.Column('total_trials', sa.Integer(), nullable=True))
    op.add_column('training_jobs', sa.Column('current_fold', sa.Integer(), nullable=True))
    op.add_column('training_jobs', sa.Column('total_folds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_jobs', 'total_folds')
    op.drop_column('training_jobs', 'current_fold')
    op.drop_column('training_jobs', 'total_trials')
    op.drop_column('training_jobs', 'current_trial')
    # ### end Alembic commands ###
